flowchart TD
%% generated in 0.00s
    urirun_connector_http_check__cli["urirun_connector_http_check.cli<br/>2 funcs"]
    urirun_connector_http_check__core["urirun_connector_http_check.core<br/>4 funcs"]
    urirun_connector_http_check__cli -->|3| urirun_connector_http_check__core
